csi:
  cephFSKernelMountOptions: ms_mode=prefer-crc
  # NOTE: Enable the driver and shapshotter if you want to use CephFS
  enableCephfsDriver: true
  enableCephfsSnapshotter: false
  enableLiveness: true
  serviceMonitor:
    enabled: true
enableDiscoveryDaemon: true
image:
  repository: ghcr.io/rook/ceph
monitoring:
  enabled: true
resources:
  requests:
    memory: 128Mi # unchangable
    cpu: 100m # unchangable
  limits: {}
