clusterName: baremetal
talosVersion: v1.9.4
domain: cluster.local
kubernetesVersion: 1.32.2
endpoint: "https://baremetal.homelab.danmanners.com:6443"

clusterPodNets:
- 10.244.0.0/16
clusterSvcNets:
- 10.96.0.0/12

cniConfig:
  name: none

additionalApiServerCertSans: &certs
  - &vip 172.20.0.10
  - 127.0.0.1

additionalMachineCertSans: *certs

nodes:
# Control Plane Nodes
## Control Plane R32-1
- hostname: cp-r32-1.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/nvme2n1
  schematic:
    customization:
      systemExtensions:
        officialExtensions: &intelExtensions
          - siderolabs/binfmt-misc
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/kata-containers
          - siderolabs/util-linux-tools
  ipAddress: 172.20.1.1
  disableSearchDomain: true
  nameservers: &nameservers
    - 172.22.0.1
    - 172.20.0.1
    - 10.3.0.1
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: enp91s0
    dhcp: false
    ignore: false
    mtu: &linux_jumbo_frames 8972
  - interface: enp3s0f0np0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  - interface: enp3s0f1np1
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.1/22
    routes:
    - network: 10.3.0.0/24
      gateway: &mgmt_gateway 172.20.0.1
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 1024
    vip:
      ip: *vip
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp91s0
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.1/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp3s0f0np0
  - interface: bond_vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp3s0f1np1
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans: &vlan_config
      - vlanId: &neutron_vlan 501
        dhcp: false
        mtu: &linux_vlan_jumbo_frames 8900
      - vlanId: &octavia_vlan 601
        dhcp: false
        mtu: *linux_vlan_jumbo_frames
  - interface: br.vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.1/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    vlans: *vlan_config
  - interface: enp88s0
    dhcp: false
    ignore: true
## Control Plane R32-2
- hostname: cp-r32-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  schematic: &intel
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/intel-ucode
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.2
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: enp6s0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.2/22
    vip:
      ip: *vip
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 10.3.0.0/24
      gateway: *mgmt_gateway
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 1025
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.2/20
    bridge:
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br.vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.2/16
    bridge:
      interfaces:
      - bond_vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans: *vlan_config
  - interface: bond_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
## Control Plane R29-1
- hostname: cp-r29-1.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  schematic: *intel
  ipAddress: 172.20.1.3
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: enp6s0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.3/22
    vip:
      ip: *vip
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 10.3.0.0/24
      gateway: *mgmt_gateway
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 1025
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.3/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br.vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.3/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans: *vlan_config
  - interface: bond_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
## Control Plane R29-2
- hostname: cp-r29-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  schematic: *intel
  ipAddress: 172.20.1.4
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: enp6s0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.4/22
    vip:
      ip: *vip
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 10.3.0.0/24
      gateway: *mgmt_gateway
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 1025
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.4/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br.vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.4/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans: *vlan_config
  - interface: bond_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
# Worker Nodes
## Worker R22
- hostname: worker-r22.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme1n1
  schematic: &amdHypervisor
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/amd-ucode
        - siderolabs/binfmt-misc
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.5
  nameservers: *nameservers
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: enp7s0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.5/22
    bridge:
      interfaces:
      - enp8s0
    routes:
    - network: 10.3.0.0/24
      gateway: *mgmt_gateway
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 1025
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.5/20
    bridge:
      interfaces:
      - enp6s0f0np0
  - interface: br.vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.5/16
    bridge:
      interfaces:
      - enp6s0f1np1
    vlans: *vlan_config
## Worker R18
- hostname: worker-r18.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme1n1
  schematic: *amdHypervisor
  ipAddress: 172.20.1.6
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: enp38s0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  - interface: enp39s0
    dhcp: false
    ignore: true
    mtu: *linux_jumbo_frames
  - interface: enp36s0f0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  - interface: enp36s0f1
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.6/22
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp38s0
    routes:
    - network: 10.3.0.0/24
      gateway: *mgmt_gateway
    # - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 256
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.6/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp36s0f0
  - interface: bond_vxlan
    dhcp: false
    mtu: *linux_jumbo_frames
    bond:
      interfaces:
      - enp36s0f1
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    vlans: *vlan_config
  - interface: br.vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.6/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    vlans: *vlan_config
## Worker R14
- hostname: worker-r14.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/sdd
  schematic:
    customization:
      systemExtensions:
        officialExtensions: *intelExtensions
  ipAddress: 172.20.1.7
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: eno1
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  - interface: enp5s0f0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  - interface: enp5s0f1
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.7/22
    bridge:
      stp:
        enabled: false
      interfaces:
      - eno1
    routes:
    - network: 10.3.0.0/24
      gateway: *mgmt_gateway
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 1025
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.7/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp5s0f1
  - interface: br.vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.7/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp5s0f0
    vlans: *vlan_config
## Worker R12
- hostname: worker-r12.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme0n1
  schematic:
    customization:
      extraKernelArgs:
      - ixgbe.allow_unsupported_sfp=1
      systemExtensions:
        officialExtensions: *intelExtensions
  ipAddress: 172.20.1.8
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Parent Interfaces set MTU to 8972
  - interface: enp5s0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  - interface: enp1s0f0
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  - interface: enp1s0f1
    dhcp: false
    ignore: false
    mtu: *linux_jumbo_frames
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.1.8/22
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp5s0
    routes:
    - network: 10.3.0.0/24
      gateway: *mgmt_gateway
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: *mgmt_gateway
      metric: 1025
  - interface: br_storage
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.20.33.8/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp1s0f0
  - interface: br.vxlan
    routes:
    - network: 0.0.0.0/0
      gateway: 172.22.0.1
      metric: 100
    dhcp: false
    mtu: *linux_jumbo_frames
    addresses:
    - 172.22.1.8/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp1s0f1
    vlans: *vlan_config

patches:
- |-
  - op: add
    path: /machine/kubelet/extraConfig
    value: 
      maxPods: 150
- |-
  - op: add
    path: /machine/sysctls
    value:
      vm.max_map_count: 524288
      fs.file-max: 131072
      fs.inotify.max_user_watches: 1048576
      fs.inotify.max_user_instances: 8192
      net.core.default_qdisc: fq             # 10Gb/s
      net.core.rmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
      net.core.wmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
      net.ipv4.tcp_congestion_control: bbr   # 10Gb/s
      net.ipv4.tcp_fastopen: 3               # Send and accept data in the opening SYN packet
      net.ipv4.tcp_mtu_probing: 1            # 10Gb/s | Jumbo frames
      net.ipv4.tcp_rmem: 4096 87380 33554432 # 10Gb/s
      net.ipv4.tcp_wmem: 4096 65536 33554432 # 10Gb/s
      net.ipv4.tcp_window_scaling: 1         # 10Gb/s
      net.ipv6.conf.all.forwarding: 1

- |-
  - op: add
    path: /machine/time
    value:
      servers: [time.cloudflare.com]
- |-
  - op: add
    path: /machine/features/hostDNS
    value:
      enabled: false
      resolveMemberNames: tru
      forwardKubeDNSToHost: false
- |-
  - op: add
    path: /machine/features
    value:
      stableHostname: true
      diskQuotaSupport: true
      rbac: true
      kubePrism:
        enabled: true
        port: 7445
- |-
  - op: add
    path: /cluster/proxy
    value:
      disabled: true

worker:
  schematic:
    customization:
      extraKernelArgs:
      - apparmor=0 # Less security, faster puter
      - init_on_alloc=0 # Less security, faster puter
      - init_on_free=0 # Less security, faster puter
      - intel_iommu=on # PCI Passthrough
      - iommu=pt # PCI Passthrough
      - mitigations=off # Less security, faster puter
      - security=none # Less security, faster puter
      - talos.auditd.disabled=1 # Less security, faster puter
  patches:
  - |-
    - op: add
      path: /machine/kubelet/nodeIP
      value:
        validSubnets: [172.20.0.0/22]

controlPlane:
  schematic: {}
  patches:
  - |-
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
        rotate-certificates: true
  - |-
    - op: add
      path: /cluster/coreDNS
      value:
        disabled: true
  - |-
    - op: remove
      path: /cluster/apiServer/admissionControl
  - |-
    - op: add
      path: /cluster/apiServer/extraArgs
      value:
        enable-aggregator-routing: true
  - |-
    - op: add
      path: /cluster/controllerManager/extraArgs
      value:
        bind-address: 0.0.0.0
  - |-
    - op: add
      path: /cluster/scheduler/extraArgs
      value:
        bind-address: 0.0.0.0
  - |-
    - op: add
      path: /machine/kubelet/nodeIP
      value:
        validSubnets: [172.20.0.0/22]
  - |-
    - op: add
      path: /cluster/etcd/advertisedSubnets
      value: [172.20.0.0/22]
  - |-
    - op: add
      path: /cluster/etcd/extraArgs
      value:
        listen-metrics-urls: http://0.0.0.0:2381
  - |-
    - op: add
      path: /machine/features/kubernetesTalosAPIAccess
      value:
        enabled: true
        allowedRoles:
          - os:admin
        allowedKubernetesNamespaces:
          - actions-runner-system
          - system-upgrade
