clusterName: baremetal
talosVersion: v1.9.3
domain: cluster.local
# talosVersion: v1.8.4 # v1.9.2 and v1.9.3 are broken AF, don't know why yet.
kubernetesVersion: 1.32.1
# kubernetesVersion: 1.31.4 # 1.32.0 is broken AF, don't know why yet.
endpoint: "https://baremetal.homelab.danmanners.com:6443"
clusterPodNets:
- 10.244.0.0/16
clusterSvcNets:
- 10.96.0.0/12

cniConfig:
  name: none

additionalApiServerCertSans:
- 127.0.0.1
- localhost
- baremetal.homelab.danmanners.com

additionalMachineCertSans:
- baremetal.homelab.danmanners.com
- localhost
- 172.20.0.10

nodes:
# Control Plane Nodes
## Control Plane R32-1
- hostname: cp-r32-1.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/nvme2n1
  ingressFirewall:
    defaultAction: accept
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/i915
        - siderolabs/intel-ucode
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.1
  disableSearchDomain: true
  nameservers: &nameservers
    - 172.20.0.1
    - 10.3.0.1
  networkInterfaces:
  # Bridge Interfaces
  - interface: enp88s0
    ignore: true
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.1/22
    vip:
      ip: 172.20.0.10
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp91s0
    routes:
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.1/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp3s0f0np0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.1/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp3s0f1np1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
## Control Plane R32-2
- hostname: cp-r32-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  ingressFirewall:
    defaultAction: accept
  schematic: &intel
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/intel-ucode
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.2
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.2/22
    vip:
      ip: 172.20.0.10
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.2/20
    bridge:
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.2/16
    bridge:
      interfaces:
      - bond_vxlan
    routes:
    - network: 172.22.0.0/16
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
## Control Plane R29-1
- hostname: cp-r29-1.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  ingressFirewall:
    defaultAction: accept
  schematic: *intel
  ipAddress: 172.20.1.3
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.3/22
    vip:
      ip: 172.20.0.10
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.3/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.3/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    routes:
    - network: 172.22.0.0/16
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
## Control Plane R29-2
- hostname: cp-r29-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  ingressFirewall:
    defaultAction: accept
  schematic: *intel
  ipAddress: 172.20.1.4
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.4/22
    vip:
      ip: 172.20.0.10
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.4/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.4/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    routes:
    - network: 172.22.0.0/16
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
# Worker Nodes
## Worker R22
- hostname: worker-r22.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme0n1
  schematic: &amdHypervisor
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/amd-ucode
        - siderolabs/binfmt-misc
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.5
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.5/22
    bridge:
      interfaces:
      - enp42s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.5/20
    bridge:
      interfaces:
      - enp4s0f0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.5/16
    bridge:
      interfaces:
      - enp4s0f1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
## Worker R18
- hostname: worker-r18.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme1n1
  ingressFirewall:
    defaultAction: accept
  schematic: *amdHypervisor
  ipAddress: 172.20.1.6
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.6/22
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp8s0
    routes:
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.6/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp10s0f0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.6/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp10s0f1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
## Worker R14
- hostname: worker-r14.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/sdd
  talosImageURL: factory.talos.dev/installer/45909762efd03de69a3f769cc4a5f5a653c10d63fdbe1dbcccf443b135d37594
  ingressFirewall:
    defaultAction: accept
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/i915
        - siderolabs/intel-ucode
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.7
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.7/22
    bridge:
      stp:
        enabled: false
      interfaces:
      - eno1
    routes:
    - network: 172.20.0.0/22
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.7/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp5s0f0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.7/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp5s0f1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900

patches:
- |-
  - op: add
    path: /machine/kubelet/extraArgs
    value:
      rotate-server-certificates: false # true
- |-
  - op: add
    path: /machine/kubelet/extraConfig
    value: 
      maxPods: 150
- |-
  - op: add
    path: /machine/sysctls
    value:
      vm.max_map_count: 524288
      fs.file-max: 131072
      fs.inotify.max_user_watches: 1048576
      fs.inotify.max_user_instances: 8192
- |-
  - op: add
    path: /machine/time
    value:
      servers: [time.cloudflare.com]
- |-
  - op: add
    path: /machine/time/bootTimeout
    value: 20s
- |-
  - op: add
    path: /machine/features
    value:
      stableHostname: true
      diskQuotaSupport: true
      rbac: true
      kubePrism:
        enabled: false
        port: 7445

worker:
  schematic: {}

controlPlane:
  schematic: {}
  patches:
  - |-
    - op: add
      path: /cluster/coreDNS
      value:
        disabled: true
  # - |-
  #   - op: remove
  #     path: /cluster/apiServer/admissionControl
  - |-
    - op: add
      path: /machine/features/hostDNS
      value:
        enabled: false
        forwardKubeDNSToHost: false
  - |-
    - op: add
      path: /cluster/apiServer/extraArgs
      value:
        feature-gates: ServerSideApply=true,AuthorizeNodeWithSelectors=false,AuthorizeWithSelectors=false
        tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - |-
    - op: add
      path: /cluster/controllerManager/extraArgs
      value:
        bind-address: 0.0.0.0
  - |-
    - op: add
      path: /cluster/scheduler/extraArgs
      value:
        bind-address: 0.0.0.0
  # - |-
  #   - op: add
  #     path: /cluster/discovery/registries/service
  #     value:
  #       disabled: false
  # - |-
  #   - op: add
  #     path: /cluster/discovery/registries/kubernetes
  #     value:
  #       disabled: false
  - |-
    - op: add
      path: /cluster/proxy
      value:
        disabled: true
  - |-
    - op: add
      path: /machine/kubelet/nodeIP
      value:
        validSubnets: [172.20.0.0/22]
  - |-
    - op: add
      path: /cluster/etcd/advertisedSubnets
      value: [172.20.0.0/22]
  - |-
    - op: add
      path: /cluster/etcd/extraArgs
      value:
        listen-metrics-urls: http://0.0.0.0:2381
        metrics: extensive
