clusterName: baremetal
talosVersion: v1.9.3
domain: cluster.local
kubernetesVersion: 1.32.1
endpoint: "https://baremetal.homelab.danmanners.com:6443"

clusterPodNets:
- 10.244.0.0/16
clusterSvcNets:
- 10.96.0.0/12

cniConfig:
  name: none

additionalApiServerCertSans: &certs
  - baremetal.homelab.danmanners.com
  - &vip 172.20.0.10
  - 127.0.0.1

additionalMachineCertSans: *certs

nodes:
# Control Plane Nodes
## Control Plane R32-1
- hostname: cp-r32-1.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/nvme2n1
  ingressFirewall: &firewall
    defaultAction: accept
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/i915
        - siderolabs/intel-ucode
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.1
  disableSearchDomain: true
  nameservers: &nameservers
    - 172.20.0.1
  networkInterfaces:
  - deviceSelector:
      hardwareAddr: 58:47:ca:79:7b:57
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.1/22
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
    vip:
      ip: *vip
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.1/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp3s0f0np0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.1/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp3s0f1np1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: enp88s0
    dhcp: false
    ignore: true
  ## Control Plane R32-2
- hostname: cp-r32-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  ingressFirewall: *firewall
  schematic: &intel
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/intel-ucode
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.2
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.2/22
    vip:
      ip: *vip
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.2/20
    bridge:
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.2/16
    bridge:
      interfaces:
      - bond_vxlan
    routes:
    - network: 172.22.0.0/16
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
## Control Plane R29-1
- hostname: cp-r29-1.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  ingressFirewall: *firewall
  schematic: *intel
  ipAddress: 172.20.1.3
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.3/22
    vip:
      ip: *vip
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.3/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.3/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    routes:
    - network: 172.22.0.0/16
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
## Control Plane R29-2
- hostname: cp-r29-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  ingressFirewall: *firewall
  schematic: *intel
  ipAddress: 172.20.1.4
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.4/22
    vip:
      ip: *vip
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp6s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.4/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_storage
    routes:
    - network: 172.20.32.0/20
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.4/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - bond_vxlan
    routes:
    - network: 172.22.0.0/16
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
# Worker Nodes
## Worker R22
- hostname: worker-r22.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme0n1
  schematic: &amdHypervisor
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/amd-ucode
        - siderolabs/binfmt-misc
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.5
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.5/22
    bridge:
      interfaces:
      - enp42s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.5/20
    bridge:
      interfaces:
      - enp4s0f0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.5/16
    bridge:
      interfaces:
      - enp4s0f1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
## Worker R18
- hostname: worker-r18.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme1n1
  ingressFirewall: *firewall
  schematic: *amdHypervisor
  ipAddress: 172.20.1.6
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.6/22
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp8s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.6/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp10s0f0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.6/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp10s0f1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
## Worker R14
- hostname: worker-r14.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/sdd
  ingressFirewall: *firewall
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/i915
        - siderolabs/intel-ucode
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.7
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.7/22
    bridge:
      stp:
        enabled: false
      interfaces:
      - eno1
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.7/20
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp5s0f0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.7/16
    bridge:
      stp:
        enabled: false
      interfaces:
      - enp5s0f1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900

patches:
- |-
  - op: add
    path: /machine/kubelet/extraConfig
    value: 
      maxPods: 150
- |-
  - op: add
    path: /machine/sysctls
    value:
      vm.max_map_count: 524288
      fs.file-max: 131072
      fs.inotify.max_user_watches: 1048576
      fs.inotify.max_user_instances: 8192
      net.core.default_qdisc: fq             # 10Gb/s
      net.core.rmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
      net.core.wmem_max: 67108864            # 10Gb/s | Cloudflared / QUIC
      net.ipv4.tcp_congestion_control: bbr   # 10Gb/s
      net.ipv4.tcp_fastopen: 3               # Send and accept data in the opening SYN packet
      net.ipv4.tcp_mtu_probing: 1            # 10Gb/s | Jumbo frames
      net.ipv4.tcp_rmem: 4096 87380 33554432 # 10Gb/s
      net.ipv4.tcp_wmem: 4096 65536 33554432 # 10Gb/s
      net.ipv4.tcp_window_scaling: 1         # 10Gb/s
- |-
  - op: add
    path: /machine/time
    value:
      servers: [time.cloudflare.com]
- |-
  - op: add
    path: /machine/features/hostDNS
    value:
      enabled: true
      resolveMemberNames: true
      forwardKubeDNSToHost: false

worker:
  schematic:
    customization:
      extraKernelArgs:
      - apparmor=0 # Less security, faster puter
      - init_on_alloc=0 # Less security, faster puter
      - init_on_free=0 # Less security, faster puter
      - intel_iommu=on # PCI Passthrough
      - iommu=pt # PCI Passthrough
      - mitigations=off # Less security, faster puter
      - security=none # Less security, faster puter
      - talos.auditd.disabled=1 # Less security, faster puter
  patches:
  - |-
    - op: add
      path: /machine/kubelet/nodeIP
      value:
        validSubnets: [172.20.0.0/22]
  - |-
    - op: add
      path: /cluster/proxy
      value:
        disabled: true
  - |-
    - op: add
      path: /machine/features
      value:
        stableHostname: true
        diskQuotaSupport: true
        rbac: true

controlPlane:
  schematic: {}
  patches:
  - |-
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
        rotate-certificates: true
  - |-
    - op: add
      path: /machine/features
      value:
        stableHostname: true
        diskQuotaSupport: true
        rbac: true
        kubePrism:
          enabled: true
          port: 7445
  - |-
    op: add
    path: /cluster
    value:
      allowSchedulingOnControlPlanes: true
  - |-
    - op: add
      path: /cluster/coreDNS
      value:
        disabled: true
  - |-
    - op: remove
      path: /cluster/apiServer/admissionControl
  - |-
    - op: add
      path: /cluster/apiServer/extraArgs
      value:
        enable-aggregator-routing: true
  - |-
    - op: add
      path: /cluster/controllerManager/extraArgs
      value:
        bind-address: 0.0.0.0
  - |-
    - op: add
      path: /cluster/scheduler/extraArgs
      value:
        bind-address: 0.0.0.0
  - |-
    - op: add
      path: /cluster/proxy
      value:
        disabled: true
  - |-
    - op: add
      path: /machine/kubelet/nodeIP
      value:
        validSubnets: [172.20.0.0/22]
  - |-
    - op: add
      path: /cluster/etcd/advertisedSubnets
      value: [172.20.0.0/22]
  - |-
    - op: add
      path: /cluster/etcd/extraArgs
      value:
        listen-metrics-urls: http://0.0.0.0:2381
  - |-
    - op: add
      path: /machine/features/kubernetesTalosAPIAccess
      value:
        enabled: true
        allowedRoles:
          - os:admin
        allowedKubernetesNamespaces:
          - actions-runner-system
          - system-upgrade
