clusterName: baremetal
talosVersion: v1.9.2
kubernetesVersion: 1.32.0
endpoint: "https://baremetal.homelab.danmanners.com:6443"
clusterPodNets:
- 10.244.0.0/16
clusterSvcNets:
- 10.96.0.0/12

cniConfig:
  name: none

additionalApiServerCertSans: &san
- 172.20.0.10
- 127.0.0.1
- baremetal.homelab.danmanners.com

additionalMachineCertSans: *san

nodes:
# Control Plane Nodes
- hostname: cp-r32-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  schematic: &miniPc
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/binfmt-misc
        - siderolabs/intel-ucode
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.2
  disableSearchDomain: true
  nameservers: &nameservers
  - 172.20.0.1
  - 10.3.0.1
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.2/22
    vip:
      ip: 172.20.0.10
    bridge:
      interfaces:
      - enp6s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.2/20
    bridge:
      interfaces:
      - bond_storage
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.2/16
    bridge:
      interfaces:
      - bond_vxlan
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
- hostname: cp-r29-1.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  schematic: *miniPc
  ipAddress: 172.20.1.3
  disableSearchDomain: true
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.3/22
    vip:
      ip: 172.20.0.10
    bridge:
      interfaces:
      - enp6s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.3/20
    bridge:
      interfaces:
      - bond_storage
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.3/16
    bridge:
      interfaces:
      - bond_vxlan
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
- hostname: cp-r29-2.homelab.danmanners.com
  controlPlane: true
  installDisk: /dev/sda
  schematic: *miniPc
  ipAddress: 172.20.1.4
  nameservers: *nameservers
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.4/22
    vip:
      ip: 172.20.0.10
    bridge:
      interfaces:
      - enp6s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.4/20
    bridge:
      interfaces:
      - bond_storage
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.4/16
    bridge:
      interfaces:
      - bond_vxlan
  # Bond Interfaces
  - interface: bond_vxlan
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp1s0
      - enp2s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
    # Neutron VLAN Interfaces
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
  - interface: bond_storage
    dhcp: false
    mtu: 8972
    bond:
      interfaces:
      - enp3s0
      - enp4s0
      mode: 802.3ad
      lacpRate: fast
      miimon: 100
      updelay: 200
      downdelay: 200
# Worker Nodes
- hostname: worker-r32-1.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme2n1
  schematic: *miniPc
  ipAddress: 172.20.1.1
  nameservers:
  - 172.20.0.1
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.1/22
    bridge:
      interfaces:
      - enp91s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.1/20
    bridge:
      interfaces:
      - enp3s0f0np0
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.1/16
    bridge:
      interfaces:
      - enp3s0f1np1
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
- hostname: worker-r22.homelab.danmanners.com
  controlPlane: false
  installDisk: /dev/nvme0n1
  schematic: &amdHypervisor
    customization:
      systemExtensions:
        officialExtensions:
        - siderolabs/amd-ucode
        - siderolabs/binfmt-misc
        - siderolabs/kata-containers
        - siderolabs/util-linux-tools
  ipAddress: 172.20.1.5
  nameservers:
  - 172.20.0.1
  networkInterfaces:
  # Bridge Interfaces
  - interface: br_mgmt
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.1.5/22
    bridge:
      interfaces:
      - enp43s0
    routes:
    - network: 0.0.0.0/0
      gateway: 172.20.0.1
  - interface: br_storage
    dhcp: false
    mtu: 8972
    addresses:
    - 172.20.33.5/20
    bridge:
      interfaces:
      - enp4s0f1
  - interface: br_vxlan
    dhcp: false
    mtu: 8972
    addresses:
    - 172.22.1.5/16
    bridge:
      interfaces:
      - enp4s0f0
    vlans:
    - vlanId: 501 # Neutron Overlay Network
      dhcp: false
      mtu: 8900
    - vlanId: 601 # Neutron Overlay Network
      dhcp: false
      mtu: 8900

patches:
- |-
  - op: add
    path: /machine/kubelet/extraArgs
    value:
      rotate-server-certificates: true
- |-
  - op: add
    path: /machine/kubelet/extraConfig
    value: 
      maxPods: 150
- |-
  - op: add
    path: /machine/kubelet/nodeIP
    value:
      validSubnets: [172.20.0.0/22]
- |-
  - op: add
    path: /machine/sysctls
    value:
      vm.max_map_count: 524288
      fs.file-max: 131072
      fs.inotify.max_user_watches: 1048576
      fs.inotify.max_user_instances: 8192
- |-
  - op: add
    path: /machine/time
    value:
      servers: [time.cloudflare.com]
- |-
  - op: add
    path: /machine/time/bootTimeout
    value: 20s

worker:
  schematic: {}
  patches:
    - |-
      - op: add
        path: /machine/features
        value:
          stableHostname: true
          diskQuotaSupport: true
          rbac: true
          kubePrism:
            enabled: true
            port: 7445

controlPlane:
  schematic: {}
  patches:
  - |-
    - op: add
      path: /cluster/coreDNS
      value:
        disabled: true
  - |-
    - op: remove
      path: /cluster/apiServer/admissionControl
  - |-
    - op: add
      path: /machine/features/hostDNS
      value:
        enabled: false
        forwardKubeDNSToHost: false
  - |-
    - op: add
      path: /cluster/apiServer/extraArgs
      value:
        feature-gates: ServerSideApply=true
        tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - |-
    - op: add
      path: /cluster/controllerManager/extraArgs
      value:
        bind-address: 0.0.0.0
  - |-
    - op: add
      path: /cluster/scheduler/extraArgs
      value:
        bind-address: 0.0.0.0
  - |-
    - op: add
      path: /cluster/discovery/registries/service
      value:
        disabled: false
  - |-
    - op: add
      path: /cluster/proxy
      value:
        disabled: true
  - |-
    - op: add
      path: /cluster/etcd/extraArgs
      value:
        listen-metrics-urls: http://0.0.0.0:2381
        metrics: extensive
  - |-
    - op: add
      path: /machine/features
      value:
        stableHostname: true
        diskQuotaSupport: true
        rbac: true
        kubePrism:
          enabled: true
          port: 7445