# Unnecessary with Ubuntu MaaS, may need this later if we get rid of MaaS.
- name: Ensure br-mgmt bridge exists
  ansible.builtin.command:
    cmd: ip link add name br-mgmt type bridge
  ignore_errors: true

- name: Configure static IP for br-mgmt
  ansible.builtin.command:
    cmd: ip addr add 192.168.0.1/24 dev br-mgmt
  ignore_errors: true

- name: Bring up the br-mgmt interface
  ansible.builtin.command:
    cmd: ip link set dev br-mgmt up
  ignore_errors: true

- name: Apply netplan configuration
  ansible.builtin.command:
    cmd: netplan apply
