- name: Ensure br-storage bridge exists
  ansible.builtin.command:
    cmd: ip link add name br-storage type bridge
  ignore_errors: true

- name: Configure static IP for br-storage if deployed on metal
  when: inventory_hostname in groups['storage_nodes'] and not virtual
  ansible.builtin.command:
    cmd: ip addr add {{ hostvars[inventory_hostname]['br_storage']['address'] }} dev br-storage
  ignore_errors: true

- name: Bring up the br-storage interface
  ansible.builtin.command:
    cmd: ip link set dev br-storage up
  ignore_errors: true

- name: Apply netplan configuration
  ansible.builtin.command:
    cmd: netplan apply
