---
- name: Ensure br-vxlan bridge exists
  ansible.builtin.command:
    cmd: ip link add name br-vxlan type bridge
  ignore_errors: true

- name: Configure static IP for br-vxlan if deployed on metal
  ansible.builtin.command:
    cmd: ip addr add {{ hostvars['br_lan']['address'] }} dev br-vxlan
  ignore_errors: true

- name: Bring up the br-vxlan interface
  ansible.builtin.command:
    cmd: ip link set dev br-vxlan up
  ignore_errors: true

- name: Apply netplan configuration
  ansible.builtin.command:
    cmd: netplan apply
