---
- name: Openstack  Prep
  hosts: openstack
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Locale
      block:
        - name: Locale | Set timezone
          community.general.timezone:
            name: "{{ timezone | default('America/New_York') }}"
    - name: Packages
      block:
        - name: Packages | Add apt repositories
          ansible.builtin.apt_repository:
            repo: "{{ item }}"
            update_cache: true
          loop: "{{ packages_repositories | default([]) }}"
        - name: Packages | Install common packages
          ansible.builtin.apt:
            name: "{{ packages_install | default([]) }}"
            install_recommends: false
        - name: Packages | Remove packages
          ansible.builtin.apt:
            name: "{{ packages_remove | default([]) }}"
            state: absent
            autoremove: true
    - name: Network
      block:
        - name: Network | Set NTP References
          ansible.builtin.include_role:
            name: linux-system-roles.timesync
          vars:
            timesync_ntp_servers:
              - hostname: time.nist.gov
                iburst: true
                pool: true

        - name: Network | Setup Storage Bridges
          when: "{{ansible_host}} in storage_nodes or compute_nodes "
          ansible.builtin.include_tasks: tasks/br-storage.yaml

        - name: Network | Setup VXLAN Bridges
          when: "{{ansible_host}} in network_nodes or compute_nodes "
          ansible.builtin.include_tasks: tasks/br-vxlan.yaml

        # - name: Network | Setup Bridge Networks
        #   ansible.builtin.include_tasks: tasks/br-mgmt.yaml
