all:
  vars:
    ansible_user: ubuntu
    nameservers:
      addresses:
      - 10.3.0.1
      search:
      - maas
      - openstack.danmanners.com

  children:
    mini_pcs:
      hosts:
        r32-2.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.2/22
            gateway: 172.20.0.1/22
            nic: enp6s0
          br_storage:
            address: 172.20.33.2/20
            gateway: 172.20.32.1/20
            nics:
            - enp3s0
            - enp4s0
          br_vxlan:
            address: 172.22.1.2/16
            gateway: 172.22.0.1/16
            nics:
            - enp1s0
            - enp2s0
          octavia:
            address: 172.31.1.2/22
          virtual: false
        r29-1.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.3/22
            gateway: 172.20.0.1/22
            nic: enp6s0
          br_storage:
            address: 172.20.33.3/20
            gateway: 172.20.32.1/20
            nics:
            - enp3s0
            - enp4s0
          br_vxlan:
            address: 172.22.1.3/16
            gateway: 172.22.0.1/16
            nics:
            - enp1s0
            - enp2s0
          octavia:
            address: 172.31.1.3/22
          virtual: false
        r29-2.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.4/22
            gateway: 172.20.0.1/22
            nic: enp6s0
          br_storage:
            address: 172.20.33.4/20
            gateway: 172.20.32.1/20
            nics:
            - enp3s0
            - enp4s0
          br_vxlan:
            address: 172.22.1.4/16
            gateway: 172.22.0.1/16
            nics:
            - enp1s0
            - enp2s0
          octavia:
            address: 172.31.1.4/22
          virtual: false
    full_sized_systems:
      hosts:
        r32-1.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.1/22
            gateway: 172.20.0.1/22
            nic: enp91s0
          br_storage:
            address: 172.20.33.1/20
            gateway: 172.20.32.1/20
            nic: enp3s0f1
          br_vxlan:
            address: 172.22.1.1/16
            gateway: 172.22.0.1/16
            nic: enp3s0f0
          virtual: false
          octavia:
            address: 172.31.1.4/22
        r22.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.5/22
            gateway: 172.20.0.1/22
            nic: enp43s0
          br_storage:
            address: 172.20.33.5/20
            gateway: 172.20.32.1/20
            nic: enp6s0f1
          br_vxlan:
            address: 172.22.1.5/16
            gateway: 172.22.0.1/16
            nic: enp6s0f0
          virtual: false
        r18.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.6/22
            gateway: 172.20.0.1/22
            nic: enp4s0
          br_storage:
            address: 172.20.33.6/20
            gateway: 172.20.32.1/20
            nic: enp12s0f1
          br_vxlan:
            address: 172.22.1.6/16
            gateway: 172.22.0.1/16
            nic: enp12s0f0
          virtual: false
        r14.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.7/22
            gateway: 172.20.0.1/22
            nic: eno1
          br_storage:
            address: 172.20.33.7/20
            gateway: 172.20.32.1/20
            nic: enp5s0f1
          br_vxlan:
            address: 172.22.1.7/16
            gateway: 172.22.0.1/16
            nic: enp5s0f0
          virtual: false
        r12.openstack.danmanners.com:
          br_mgmt:
            address: 172.20.1.8/22
            gateway: 172.20.0.1/22
            nic: enp5s0
          br_storage:
            address: 172.20.33.8/20
            gateway: 172.20.32.1/20
            nic: enp1s0f1
          br_vxlan:
            address: 172.22.1.8/16
            gateway: 172.22.0.1/16
            nic: enp1s0f0
          virtual: false

    openstack:
      children:

        mini_pcs:
          hosts:
            r32-2.openstack.danmanners.com:
            r29-1.openstack.danmanners.com:
            r29-2.openstack.danmanners.com:


        octavia:
          hosts:
            r32-1.openstack.danmanners.com:
            r32-2.openstack.danmanners.com:
            r29-1.openstack.danmanners.com:
            r29-2.openstack.danmanners.com:


        infra_nodes:
          hosts:
            r29-1.openstack.danmanners.com:
            r29-2.openstack.danmanners.com:
            r32-2.openstack.danmanners.com:


        storage_nodes:
          hosts:
            r32-1.openstack.danmanners.com:
            r22.openstack.danmanners.com:
            r18.openstack.danmanners.com:
            r14.openstack.danmanners.com:


        nova_nodes:
          hosts:
            r32-1.openstack.danmanners.com:
            r22.openstack.danmanners.com:
            r18.openstack.danmanners.com:
            r14.openstack.danmanners.com:
            r12.openstack.danmanners.com:
